###
#  MIT License
#
#  Copyright (c) 2020 Alessandro Tondo
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
#  documentation files (the "Software"), to deal in the Software without restriction, including without limitation
#  the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
#  to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in all copies or substantial portions of
#  the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
#  THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#  TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#  SOFTWARE.
#

name: CMake-CI-macOS

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Test on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
    - name: Clone GTest
      shell: bash
      working-directory: ${{runner.workspace}}
      run: git clone https://github.com/google/googletest.git

    - name: Create GTest Build Environment
      shell: bash
      working-directory: ${{runner.workspace}}/googletest
      run: cmake -E make_directory build

    - name: Configure GTest CMake
      shell: bash
      working-directory: ${{runner.workspace}}/googletest/build
      run: cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS=-std=c++11 -DBUILD_SHARED_LIBS=ON

    - name: Install GTest
      shell: bash
      working-directory: ${{runner.workspace}}/googletest/build
      run: sudo cmake --build . --config $BUILD_TYPE --target install

    - name: Checkout
      uses: actions/checkout@v2

    - name: Create Build Environment
      shell: bash
      working-directory: ${{runner.workspace}}/serial
      run: cmake -E make_directory build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/serial/build
      run: cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=ON

    - name: Build
      shell: bash
      working-directory: ${{runner.workspace}}/serial/build
      run: sudo cmake --build . --config $BUILD_TYPE --target install

    - name: Test
      shell: bash
      working-directory: ${{runner.workspace}}/serial/build
      run: ctest -C $BUILD_TYPE --output-on-failure
